services:
  llama:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    volumes:
      - ./models/:/root/.cache/llama.cpp/
    ports:
      - "8080:8080"
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      # -hf unsloth/phi-4-GGUF:Q4_K_M
    command: >
      -hf TheBloke/Mistral-7B-Instruct-v0.1-GGUF:mistral-7b-instruct-v0.1.Q4_K_M.gguf
      --port 8080
      --host 0.0.0.0
      --flash-attn
      --n-gpu-layers 99
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
      - 6335:6335
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage


configs:
  qdrant_config:
    content: |
      log_level: INFO